{% set name = "simde" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simd-everywhere/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c63e6c61392e324728da1c7e5de308cb31410908993a769594f5e21ff8de962b

build:
  number: 0
  ignore_run_exports_from:
    # Since this package does not ship any compiled code, we do not need any
    # compatibility with the compiler used at runtime.
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - meson
  host:
  run:

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/include/simde/simde-common.h  # [not win]
    - if not exist %LIBRARY_INC%\simde\simde-common.h exit 1  # [win]

about:
  home: https://github.com/simd-everywhere/simde.git
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Implementations of SIMD instruction sets for systems which don't natively support them.

extra:
  recipe-maintainers:
    - jcarpent
